### PR TITLE
tests/functional: Fix functional test 053 to be skiped

### PR DESCRIPTION
**Pull request by fuku-ys**
This test was affected by issue https://github.com/sheepdog/sheepdog/issues/103

Signed-off-by: Yasuhito Fukuda <fukuda.yasuhito@po.ntts.co.jp>
Signed-off-by: Satoshi Kuramochi <act.kura@gmail.com>

### CODE REVIEW

**Comment by mitake** [comment]
@fuku-ys gateway only cluster clearly makes no sence (actually such a situation isn't allowed because it produces data wipe bug). How about just removing the test?

**Comment by sa-kura** [comment]
@mitake  This test detected the bug(issue #103 ).
So it's better not remove this test until the bug is fix.

**Comment by mitake** [comment]
@sa-kura ok, them merge it for now.

**Comment by tmenjo** [comment]
I agree with @sa-kura. Indeed gateway-*only* cluster is useless as @mitake says, but this test could check whether a cluster *containing* gateway can be formatted or not. Now it cannot be so, but I think this behavior may be confusing. So it is better to let this test remain than to remove until #103 is solved.

\# The comment in the testing script may also be confusing... :(

p.s. I ran the 4 unmerged functional tests i.e. #259 (this PR), #260, #263 and #277 then confirmed that they were not failed.

**Comment by tmenjo** [comment]
Oh, sorry that my comment is late a little... Thanks @mitake!

**Pull request merged**
