### PR TITLE
tests/functional: Remove 037 and 038

### PR DESCRIPTION
**Pull request by tmenjo**
Functional tests 037 and 038 try to kill sheeps during cluster being formatted. According to the comments, this simulates node failure just after format.

This commit removes these two tests. I think they are needless because they are (1) unstable: sometimes succeeed, sometimes fail; (2) meaningless: in such a situation, I think an operator should rather redo the process of formating cluster from the beginning than continue running the cluster forcibly.

Signed-off-by: Takashi Menjo &lt;menjo.takashi@lab.ntt.co.jp&gt;

### CODE REVIEW

**Comment by tmenjo** [comment]
Update commit log.

**Comment by tmenjo** [comment]
@mitake, may I merge this?

**Comment by mitake** [comment]
@tmenjo sorry, I missed it. Merged, thanks.

**Comment by tmenjo** [comment]
@mitake, thanks!

**Pull request merged**
