### PR TITLE
Fixes the issue 164

### PR DESCRIPTION
**Pull request by mitake**
This branch will solve the problem reported in https://github.com/sheepdog/sheepdog/issues/164

Could you try it, @sirio81 ?

### CODE REVIEW

**Comment by sirio81** [comment]
I cant't start sheep: 

Sep 21 11:24:08   INFO [main] md_add_disk(368) /mnt/sheep/0, vdisk nr 413, total disk 1
Sep 21 11:24:08   INFO [main] md_add_disk(368) /mnt/sheep/1, vdisk nr 413, total disk 2
Sep 21 11:24:08   INFO [main] md_add_disk(368) /mnt/sheep/2, vdisk nr 1741, total disk 3
Sep 21 11:24:08  ERROR [main] init_config_file(147) Designation of before a restart and a vnodes option is different.

My build options are

--enable-zookeeper --disable-corosync --enable-diskvnodes

sheep -v
Sheepdog daemon version 0.9.0_282_g22cf1c2

**Comment by mitake** [comment]
It seems that you format your cluster with fixed vnodes but launched sheep with autovinodes mode (or formatted with autovnodes mode and launched with fixed vnodes mode).

Could you try after format your cluster?

**Comment by sirio81** [comment]
Ops, sorry, I had to clear my cluster first.
It works.
I killed the guest and got no delay on ssh and no messages in the log.

Thank you.

**Comment by mitake** [comment]
Thanks for your testing, @sirio81 . Merged it.

**Pull request merged**
