### PR TITLE
RFC: sheep: cache eventfd for local request in thread local storage

### PR DESCRIPTION
**Pull request by mitake**
Creating a fd must be serialized because of the minimum available fd
allocation rule of Posix, so current implementation of the local
request is bad for multicore scalability.

Signed-off-by: Hitoshi Mitake <mitake.hitoshi@lab.ntt.co.jp>

/cc @tmenjo I'm not measuring the performance but this change would introduce some difference.

### CODE REVIEW

**Comment by tmenjo** [comment]
@mitake: Looks almost good to me, except closing eventfd. Is it automatically closed when the thread is destroyed?

**Comment by mitake** [comment]
@tmenjo no, the fd will remain forever. This commit currently doesn't consider the case of dynamic workqueue. If we can check the commit really contributes to performance improvement, I can clean up the leak problem.

**Comment by mitake** [comment]
I added the mechanism for closing fds correctly.

**Comment by tmenjo** [comment]
How about using pthread_key_create [1] to set destructor? I think it's easier to maintain.

[1] https://linux.die.net/man/3/pthread_key_create

**Comment by mitake** [comment]
Ah I forgot the API, thanks. Anyway, this isn't an emergent change. I'll update it in the near future.

**Pull request closed without merging**
