### PR TITLE
new options for controlling requests during VDI deletion

### PR DESCRIPTION
**Pull request by mitake**
/cc @tmenjo

### CODE REVIEW

**Comment by tmenjo** [comment]
@mitake Thanks for your notification. I understand that this is for controlling the number of async_update_obj_refcnt_work put concurrently onto workqueue by copy-on-write, to mitigate possibility of deadlock.

**Comment by mitake** [comment]
@tmenjo yes, and it is also useful for controlling network and disk I/O resource consumption caused by VDI deletion. Typically the operation can consume much resources.

**Comment by mitake** [comment]
It seems that 068 is failing, but the test can be passed on my local environment. It would be fleaky one.

**Comment by tmenjo** [comment]
I think so. Now this is ready for merge enough.

**Comment by mitake** [comment]
Merged, thanks.

**Pull request merged**
