### PR TITLE
cleanup messages about missing features

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by mitake** [comment]
Do we really need it? I think the messages are not so harmful.

**Comment by vtolstov** [comment]
i don't see any benefits of this messages, but when i looks into log i see it and thinks that something wrong =)
And i don't known any software that on start says about missing configured/compiled features.

**Comment by mitake** [comment]
ok, then could you remove the logging in the functions e.g. http_init()? it is more simpler solution.

**Comment by vtolstov** [comment]
@mitake if you prefer, ok, but i think completely remove stub functions that logs messages.

**Comment by mitake** [comment]
both of them are ok for me, please do it as you like

**Comment by mitake** [comment]
Pulled, thanks. Could you exclude http_options in sheep.c in another commit?

**Comment by vtolstov** [comment]
@mitake do you mean this line: 
```
if (http_options && http_init(http_options) != 0)
```

**Comment by mitake** [comment]
yes
2015/09/08 17:28 "Vasiliy Tolstov" <notifications@github.com>:

**Comment by vtolstov** [comment]
@mitake ok, pr #151

**Pull request merged**
