### PR TITLE
tests: Create an environment for auto-testing with CI

### PR DESCRIPTION
**Pull request by sheepdog-tester**
In addition, some tests have been modified.

### CODE REVIEW

**Comment by mitake** [comment]
Could you add some detailed explanations of the modifications to the commit logs?

**Comment by sheepdog-tester** [comment]
I added the details in the commit logs.

**Comment by mitake** [comment]
merged, thanks

**Comment by sheepdog-tester** [comment]
Thanks.
Now, Travis CI is activated for this repository.

**Pull request merged**
