### PR TITLE
sheep: disable async ledger update for VID recycling mode

### PR DESCRIPTION
**Pull request by mitake**
The async ledger update can cause data loss because the process of
decrementing reference count can be delayed and the target VID can be
used for newly created VDIs. This commit forbids the async update if
the cluster is formatted with VID recycling mode.

Fixes https://github.com/sheepdog/sheepdog/issues/315

Signed-off-by: Hitoshi Mitake <mitake.hitoshi@lab.ntt.co.jp>

### CODE REVIEW

**Comment by mitake** [comment]
@tmenjo could you check this PR? I tested it with your script and the problem seems to be fixed.

**Comment by tmenjo** [comment]
@mitake: This is a good PR! I will review and test this soon. Please stay tuned.

**Comment by tmenjo** [comment]
@mitake: This PR looks good to me, and my test result is green. So I think this is ready to be merged.

**Comment by mitake** [comment]
@tmenjo thanks for your review, merged

**Pull request merged**
