### PR TITLE
issue 408: Imbalanced storage utilization among multiple disks

### PR DESCRIPTION
**Pull request by ShienXie**
Signed-off-by: Shien Xie <shien.xie@kaixiangtech.com>

The positions calculated by hash functions are not evenly spread on the ring. The situation will be worsen if the positions are hashed twice. For example, if the node has multiple disks and imbalance among disks is worse than imbalance among nodes.

The solution is to reduce the size of vdisk from 1G to 16M. The following is the result. Comparing this to the result described in the issue 408, the imbalance problem is greatly relieved. Test shows performance is also increased around 3%~5%, perhaps because the load is more evenly spreaded.

Test result: 16M vdisk size
Node 0:
0      417 GB  199 GB  218 GB   47%    /sheep/disk0
1      417 GB  198 GB  219 GB   47%    /sheep/disk1
2      417 GB  194 GB  223 GB   46%    /sheep/disk2
3      417 GB  194 GB  224 GB   46%    /sheep/disk3
Node 1:
0      417 GB  158 GB  259 GB   37%    /sheep/disk0
1      417 GB  157 GB  260 GB   37%    /sheep/disk1
2      417 GB  168 GB  249 GB   40%    /sheep/disk2
3      417 GB  161 GB  256 GB   38%    /sheep/disk3
Node 2:
0      417 GB  210 GB  207 GB   50%    /sheep/disk0
1      417 GB  192 GB  225 GB   46%    /sheep/disk1
2      417 GB  187 GB  230 GB   44%    /sheep/disk2
3      417 GB  201 GB  217 GB   48%    /sheep/disk3
Node 3:
0      417 GB  181 GB  236 GB   43%    /sheep/disk0
1      417 GB  185 GB  232 GB   44%    /sheep/disk1
2      417 GB  191 GB  226 GB   45%    /sheep/disk2
3      417 GB  191 GB  226 GB   45%    /sheep/disk3
Node 4:
0      417 GB  198 GB  219 GB   47%    /sheep/disk0
1      417 GB  194 GB  223 GB   46%    /sheep/disk1
2      417 GB  186 GB  231 GB   44%    /sheep/disk2
3      417 GB  180 GB  237 GB   43%    /sheep/disk3
Node 5:
0      417 GB  223 GB  194 GB   53%    /sheep/disk0
1      417 GB  223 GB  194 GB   53%    /sheep/disk1
2      417 GB  209 GB  208 GB   50%    /sheep/disk2
3      417 GB  208 GB  209 GB   49%    /sheep/disk3
Node 6:
0      417 GB  183 GB  235 GB   43%    /sheep/disk0
1      417 GB  178 GB  239 GB   42%    /sheep/disk1
2      417 GB  168 GB  249 GB   40%    /sheep/disk2
3      417 GB  165 GB  252 GB   39%    /sheep/disk3
Node 7:
0      417 GB  164 GB  253 GB   39%    /sheep/disk0
1      417 GB  173 GB  244 GB   41%    /sheep/disk1
2      417 GB  167 GB  250 GB   40%    /sheep/disk2
3      417 GB  176 GB  241 GB   42%    /sheep/disk3
Node 8:
0      417 GB  196 GB  221 GB   46%    /sheep/disk0
1      417 GB  198 GB  220 GB   47%    /sheep/disk1
2      417 GB  192 GB  225 GB   45%    /sheep/disk2
3      417 GB  195 GB  222 GB   46%    /sheep/disk3
Node 9:
0      417 GB  237 GB  180 GB   56%    /sheep/disk0
1      417 GB  232 GB  185 GB   55%    /sheep/disk1
2      417 GB  236 GB  181 GB   56%    /sheep/disk2
3      417 GB  259 GB  159 GB   61%    /sheep/disk3
Node 10:
0      417 GB  230 GB  187 GB   55%    /sheep/disk0
1      417 GB  220 GB  197 GB   52%    /sheep/disk1
2      417 GB  205 GB  212 GB   49%    /sheep/disk2
3      417 GB  221 GB  197 GB   52%    /sheep/disk3
Node 11:
0      417 GB  186 GB  231 GB   44%    /sheep/disk0
1      417 GB  188 GB  229 GB   45%    /sheep/disk1
2      417 GB  183 GB  234 GB   43%    /sheep/disk2
3      417 GB  182 GB  236 GB   43%    /sheep/disk3
Node 12:
0      696 GB  299 GB  396 GB   43%    /sheep/disk0
1      696 GB  297 GB  399 GB   42%    /sheep/disk1
2      696 GB  301 GB  395 GB   43%    /sheep/disk2
3      696 GB  305 GB  390 GB   43%    /sheep/disk3
Node 13:
0      696 GB  313 GB  382 GB   45%    /sheep/disk0
1      696 GB  306 GB  390 GB   43%    /sheep/disk1
2      696 GB  305 GB  391 GB   43%    /sheep/disk2
3      696 GB  297 GB  398 GB   42%    /sheep/disk3
Node 14:
0      696 GB  321 GB  375 GB   46%    /sheep/disk0
1      696 GB  311 GB  385 GB   44%    /sheep/disk1
2      696 GB  332 GB  364 GB   47%    /sheep/disk2
3      696 GB  319 GB  377 GB   45%    /sheep/disk3
Node 15:
0      696 GB  344 GB  352 GB   49%    /sheep/disk0
1      696 GB  318 GB  377 GB   45%    /sheep/disk1
2      696 GB  333 GB  363 GB   47%    /sheep/disk2
3      696 GB  329 GB  367 GB   47%    /sheep/disk3
Node 16:
0      696 GB  304 GB  392 GB   43%    /sheep/disk0
1      696 GB  307 GB  388 GB   44%    /sheep/disk1
2      696 GB  301 GB  394 GB   43%    /sheep/disk2
3      696 GB  323 GB  373 GB   46%    /sheep/disk3
Node 17:
0      696 GB  319 GB  377 GB   45%    /sheep/disk0
1      696 GB  316 GB  379 GB   45%    /sheep/disk1
2      696 GB  316 GB  379 GB   45%    /sheep/disk2
3      696 GB  312 GB  384 GB   44%    /sheep/disk3
Node 18:
0      696 GB  344 GB  352 GB   49%    /sheep/disk0
1      696 GB  330 GB  365 GB   47%    /sheep/disk1
2      696 GB  343 GB  352 GB   49%    /sheep/disk2
3      696 GB  355 GB  340 GB   51%    /sheep/disk3
Node 19:
0      696 GB  336 GB  360 GB   48%    /sheep/disk0
1      696 GB  350 GB  346 GB   50%    /sheep/disk1
2      696 GB  334 GB  361 GB   48%    /sheep/disk2
3      696 GB  358 GB  338 GB   51%    /sheep/disk3
Node 20:
0      696 GB  327 GB  368 GB   47%    /sheep/disk0
1      696 GB  353 GB  342 GB   50%    /sheep/disk1
2      696 GB  339 GB  357 GB   48%    /sheep/disk2
3      696 GB  351 GB  344 GB   50%    /sheep/disk3
Node 21:
0      696 GB  294 GB  402 GB   42%    /sheep/disk0
1      696 GB  297 GB  399 GB   42%    /sheep/disk1
2      696 GB  295 GB  400 GB   42%    /sheep/disk2
3      696 GB  292 GB  404 GB   41%    /sheep/disk3
Node 22:
0      696 GB  322 GB  374 GB   46%    /sheep/disk0
1      696 GB  326 GB  370 GB   46%    /sheep/disk1
2      696 GB  321 GB  375 GB   46%    /sheep/disk2
3      696 GB  321 GB  374 GB   46%    /sheep/disk3
Node 23:
0      696 GB  297 GB  398 GB   42%    /sheep/disk0
1      696 GB  270 GB  426 GB   38%    /sheep/disk1
2      696 GB  289 GB  406 GB   41%    /sheep/disk2
3      696 GB  286 GB  410 GB   41%    /sheep/disk3

### CODE REVIEW

**Comment by ShienXie** [comment]
The "failed" functional test is actually a good example that shows how the fix works!
With the fix, the storage on both drives were equally used by 17%. Without the fix, one path is 33% used but the other is only 1% used.

114  Test md plug and sparse object - output mismatch (see 114.out.bad)
--- 114.out	2017-06-22 17:23:53.862024361 +0000
+++ 114.out.bad	2017-06-22 17:45:39.582312778 +0000
@@ -33,35 +33,35 @@
 STORE/1/80709b5a00000000 6144 12587576
 STORE/1/80709d0d00000000 6144 12587576
 Id	Size	Used	Avail	Use%	Path
- 0	229 MB	76 MB	153 MB	 33%	STORE/1
- 1	229 MB	4.0 MB	225 MB	  1%	STORE/2
+ 0	229 MB	40 MB	189 MB	 17%	STORE/1
+ 1	229 MB	40 MB	189 MB	 17%	STORE/2

**Comment by mitake** [comment]
@ShienXie merged, thanks! Yes, the failed test can be an evidence of the effectiveness from this change. It is great if you can fix the test, too :)

**Comment by kazuhisya** [comment]
Hi, @ShienXie and @mitake 

I thought this fix is great works.
BTW, as you guys said, after this merge I am experiencing that the test will fail 100% every time.
It is `057`, `064` and `114`.

Will you fix test case in a few days or nearly future? 
If you'd like I will try to prepare this fix.

**Comment by ShienXie** [comment]
@mitake I am trying to fix the functional test 114. I noticed that in function _listFiles(), stat command is being called with %b and %B and the AWK command calculate the product of those two ($2*$3), which is the actual size that the file allocated on the disk. Then, this size is saved in 114.out for futuring testing. Is there any reason for doing that? It looks like this size can vary for two identical files. For example, after the second disk is plugged in, some files (vdi files starts with 80xxxxxxxxxxxxx) are relocated from STORE/1 to STORE/2. Although those files are identical, the actual size that these files allocated on the the file system are changed from 6144 to 8192. Moreover, the actual size can also fluctuate slightly for different tests. Based on my testing, sometimes the actual size of vdi files after relocation can be 9216. I think this is because linux's sparse file system. If the data offset inside the file is different, the actual file size will be different too. So, I suggest not to include actual size in this test. We can use md5sum instead, if you feel it is necessary.

**Comment by ShienXie** [comment]
@kazuhisya Hi kazuhisya, yes, I have already started to work on the fix. 057, 064 are easy to fix, just update the *.out file should work. However, 114 is a little bit tricky. Please see my reply above and let me know if you have any suggestions/questions.

**Comment by ShienXie** [comment]
@mitake The reason why the actual size of vdi files varies after relocation is: sometimes it contains an ETB0 block.
==========================================================
debugfs:  stat 8070948e00000000
Inode: 21   Type: regular    Mode:  0640   Flags: 0x80000
Generation: 2314715037    Version: 0x00000001
User:     0   Group:     0   Size: 12587576
File ACL: 0    Directory ACL: 0
Links: 1   Blockcount: 16
Fragment:  Address: 0    Number: 0    Size: 0
ctime: 0x5952c92c -- Tue Jun 27 14:07:56 2017
atime: 0x5952c92b -- Tue Jun 27 14:07:55 2017
mtime: 0x5952c92c -- Tue Jun 27 14:07:56 2017
EXTENTS:
(0-7):55297-55304

debugfs:  blocks 8070948e00000000
55297 55298 55299 55300 55301 55302 55303 55304

==========================================================
debugfs:  stat 8070948e00000000
Inode: 22   Type: regular    Mode:  0640   Flags: 0x80000
Generation: 3325085807    Version: 0x00000001
User:     0   Group:     0   Size: 12587576
File ACL: 0    Directory ACL: 0
Links: 1   Blockcount: 18
Fragment:  Address: 0    Number: 0    Size: 0
ctime: 0x5952c813 -- Tue Jun 27 14:03:15 2017
atime: 0x5952c813 -- Tue Jun 27 14:03:15 2017
mtime: 0x5952c813 -- Tue Jun 27 14:03:15 2017
EXTENTS:
**(ETB0):8452**, (0-7):63489-63496

debugfs:  blocks 8070948e00000000
**8452** 63489 63490 63491 63492 63493 63494 63495 63496

**Comment by kazuhisya** [comment]
@ShienXie Thank you for reply.
IMHO, what we want to check with this test is only whether it is **a sparse file or not**.
So, I think that we can hide values and compare simply.

like this:

```code
stat -c "%n %b %B %s" "$i"/* |\
        awk '{
                if ($2*$3-'${extra_blocksize}' == $4){
                        print $1,"not-sparse"
                } else {
                        print $1,"sparse"
                }
        }'|\
...
```


What do you think it?

/cc @mitake

**Comment by ShienXie** [comment]
@kazuhisya @mitake I feel we are more interested in testing the accuracy of recovery than figuring out if it is a sparse file. Maybe we should test md5sum before and after file relocation?

**Comment by mitake** [comment]
@ShienXie @kazuhisya the purpose of test 114 is checking that md can handle sparse file correctly. In the past, it couldn't handle so we added the test case. So checking the file is sparse or not is required. But of course including the concrete numbers in 114.out isn't a good idea. Adding a check like @kazuhisya 's idea or just ensuring `%b * %B < %s` (in terms of stat) would be nice.

**Comment by ShienXie** [comment]
@mitake OK, I will fix it.

**Comment by ShienXie** [comment]
I've created a PR. It seems that Travis CI test always has problems... Did I do anything wrong?

**Pull request merged**
