### PR TITLE
fix corosync depends

### PR DESCRIPTION
**Pull request by vtolstov**
allow to build with corosync 2.x

Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by mitake** [comment]
Thanks a lot, but it caused build error on my environment:
```
  CCLD     sheep
cluster/corosync.o: In function `send_message':
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:189: undefined reference to `cpg_mcast_joined'
cluster/corosync.o: In function `corosync_join':
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:620: undefined reference to `cpg_join'
cluster/corosync.o: In function `corosync_get_local_addr':
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:136: undefined reference to `corosync_cfg_get_node_addrs'
cluster/corosync.o: In function `corosync_init':
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:699: undefined reference to `cpg_initialize'
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:721: undefined reference to `corosync_cfg_initialize'
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:727: undefined reference to `corosync_cfg_local_get'
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:736: undefined reference to `cpg_fd_get'
cluster/corosync.o: In function `corosync_handler':
/home/mitake/github/sheepdog.git/sheep/cluster/corosync.c:677: undefined reference to `cpg_dispatch'
collect2: error: ld returned 1 exit status
```

**Comment by vtolstov** [comment]
with last patch, all works fine

**Comment by vtolstov** [comment]
ping...

**Comment by mitake** [comment]
Seems good, could you squash the two commits into one? Then I can merge the PR.

**Comment by vtolstov** [comment]
i'm squash commits into one

**Comment by mitake** [comment]
Pulled, thanks!

**Pull request merged**
