### PR TITLE
sheepdog stable release v1.0.2_rc0

### PR DESCRIPTION
**Pull request by tmenjo**
**Please DO NOT merge this PR.** This is only for review.

See also #353.

## CHANGELOG (draft)
IMPORTANT CHANGES:
 - Unlimited workqueue is now removed and changed to dynamic one. This is for sheep not to consume a huge amount of memory by creating new threads infinitely under heavy load, and to avoid being shot by OOM-killer.
 - zk\_control now can purge znodes within 24 hours. It purges znodes created before the given threshold. This is useful if tens of thousands of znodes are created in a day.

SHEEP COMMAND INTERFACE:
 - New option "-x" to set the maximum number of threads for dynamic workqueue. (default: decided by "max(#nodes,#cores,16)\*2" formula)

ZK\_CONTROL COMMAND INTERFACE:
 - The "purge" subcommand can take a non-negative interger as a threshold in seconds. (default: 86400 (24 hours))

LOGGING:
 - Print object IDs in 16-digit zero-padded hexadecimal to sheep.log.

### CODE REVIEW

**Comment by tmenjo** [comment]
CI may fail but AFAIU it is only for master, not stable branches.

**Comment by tmenjo** [comment]
@mitake May I work on this? If so, I will continue my work directly on stable-1.0 branch.

**Comment by vtolstov** [comment]
Does it possible to consume max memory used by sheep workqueue thread ?
So I can determine or maximum threads or limit other processes to avoid oom
killer?

23 Янв 2017 г. 13:15 пользователь "Takashi Menjo" <notifications@github.com>
написал:

**Comment by tmenjo** [comment]
It's possible to limit **the number of threads** for dynamic work queue by -x option. For example, if you give `-x 100` to a sheep, each dynamic work queue (net, gway, io, rw and async_req) in that sheep has up to 100 threads.

Though you cannot directly limit "max memory used by sheep workqueue thread", this will be helpful to avoid OOM-killer.

**Comment by vtolstov** [comment]
@tmenjo thats fine, but how much memory used by one thread?
4Mb max or more? Or it maximum like block size shift?

**Comment by tmenjo** [comment]
@vtolstov I think it is difficult to estimate because it is different depending on environment. So we should test and tune memory usage (and performance) before deploying to production.

**Comment by vtolstov** [comment]
@tmenjo but for maximum, does it possible that thread uses more memory then maximum block ?

**Comment by mitake** [comment]
@tmenjo looks good to me

**Comment by tmenjo** [comment]
@vtolstov Yes; memory for **thread's stack** is needed. Its size depends on "ulimit -s".

I think you mean memory for **struct request** which contains a data buffer whose size is equal to the data block size (2\*\*22 default) if it is a read/write request. Of course this is also needed, but I think the amount of memory for this does not increase so much when the number of threads increases because only a pointer to the data buffer is exchanged between threads.

**Comment by tmenjo** [comment]
PR updated. Previous version is [here](https://github.com/tmenjo/sheepdog/tree/for-v1.0.2-1).

Commit "rpm: support for systemd and sysvinit" 454b84a0dc7f61bccff5c435f7a742c9bd14e94f is cherry-picked.

## diff

```diff
diff --git a/sheepdog.spec.in b/sheepdog.spec.in
index 1756087..2e43c2a 100644
--- a/sheepdog.spec.in
+++ b/sheepdog.spec.in
@@ -1,3 +1,5 @@
+%define use_systemd (0%{?fedora} && 0%{?fedora} >= 18) || (0%{?rhel} && 0%{?rhel} >= 7)
+
 Name: sheepdog
 Summary: The Sheepdog Distributed Storage System for QEMU
 Version: @version@
@@ -9,9 +11,14 @@ Source0: http://downloads.sourceforge.net/project/sheepdog/%{name}/%{version}/%{
 
 # Runtime bits
 Requires: corosync %{_requires}
+%if %{use_systemd}
+Requires: systemd
+BuildRequires: systemd-units
+%else
 Requires(post): chkconfig
 Requires(preun): chkconfig
 Requires(preun): initscripts
+%endif
 
 # Build bits
 BuildRequires: autoconf automake
@@ -37,6 +44,11 @@ rm -rf %{buildroot}
 
 make install DESTDIR=%{buildroot}
 
+# drop init file (systemd only)
+%if %{use_systemd}
+rm -f $RPM_BUILD_ROOT%{_initddir}/sheepdog
+%endif
+
 ## tree fixup
 # drop static libs
 rm -f %{buildroot}%{_libdir}/*.a
@@ -45,20 +57,35 @@ rm -f %{buildroot}%{_libdir}/*.a
 rm -rf %{buildroot}
 
 %post
+%if %{use_systemd}
+/usr/bin/systemctl preset sheepdog.service >/dev/null 2>&1 || :
+%else
 /sbin/chkconfig --add sheepdog
+%endif
 ln -s -f %{_bindir}/dog %{_bindir}/collie
 
 %preun
+
 if [ $1 -eq 0 ] ; then
-	/sbin/service sheepdog stop >/dev/null 2>&1
-	/sbin/chkconfig --del sheepdog
+    %if %use_systemd
+    /usr/bin/systemctl --no-reload disable sheepdog.service >/dev/null 2>&1 || :
+    /usr/bin/systemctl stop sheepdog.service >/dev/null 2>&1 || :
+    %else
+    /sbin/service sheepdog stop >/dev/null 2>&1
+    /sbin/chkconfig --del sheepdog
+    %endif
 fi
 
 %postun
 if [ "$1" -ge "1" ] ; then
-	/sbin/service sheepdog condrestart >/dev/null 2>&1 || :
+    %if %use_systemd
+    /usr/bin/systemctl daemon-reload >/dev/null 2>&1 || :
+    /usr/bin/systemctl try-restart sheepdog.service >/dev/null 2>&1 || :
+    %else
+    /sbin/service sheepdog condrestart >/dev/null 2>&1 || :
+    %endif
 else
-	rm -f /usr/sbin/collie
+    rm -f /usr/sbin/collie
 fi
 
 %files
@@ -68,16 +95,11 @@ fi
 %{_sbindir}/sheepfs
 %{_bindir}/dog
 %{_sbindir}/shepherd
-%if 0%{_have_zookeeper}
-	%{_sbindir}/zk_control
-%endif
-%attr(755,-,-)%config %{_initddir}/sheepdog
 %dir %{_localstatedir}/lib/sheepdog
 %config %{_sysconfdir}/bash_completion.d/dog
 %{_mandir}/man8/sheep.8*
 %{_mandir}/man8/sheepfs.8*
 %{_mandir}/man8/dog.8*
-%{_prefix}/lib/systemd/system/sheepdog.service
 %dir %{_includedir}/sheepdog
 %{_includedir}/sheepdog/internal.h
 %{_includedir}/sheepdog/list.h
@@ -86,6 +108,14 @@ fi
 %{_includedir}/sheepdog/util.h
 %{_libdir}/libsheepdog.la
 %{_libdir}/libsheepdog.so
+%if 0%{_have_zookeeper}
+%{_sbindir}/zk_control
+%endif
+%if %{use_systemd}
+%{_unitdir}/sheepdog.service
+%else
+%attr(755,-,-)%config %{_initddir}/sheepdog
+%endif
 
 %changelog
 * @date@ Autotools generated version <nobody@nowhere.org> - @version@-1.@alphatag@
```

**Comment by tmenjo** [comment]
Fast-forwarded into stable-1.0.

**Pull request merged**
