### PR TITLE
sheepdog stable release v0.9.5_rc0

### PR DESCRIPTION
**Pull request by tmenjo**
**Please DO NOT merge this PR.** This is only for review.

See also #354.

## CHANGELOG (draft)
IMPORTANT CHANGES:
 - Unlimited workqueue is now removed and changed to dynamic one. This is for sheep not to consume a huge amount of memory by creating new threads infinitely under heavy load, and to avoid being shot by OOM-killer.
 - zk\_control now can purge znodes within 24 hours. It purges znodes created before the given threshold. This is useful if tens of thousands of znodes are created in a day.

SHEEP COMMAND INTERFACE:
 - New option "-x" to set the maximum number of threads for dynamic workqueue. (default: decided by "max(#nodes,#cores,16)\*2" formula)

ZK\_CONTROL COMMAND INTERFACE:
 - The "purge" subcommand can take a non-negative interger as a threshold in seconds. (default: 86400 (24 hours))

LOGGING:
 - Print object IDs in 16-digit zero-padded hexadecimal to sheep.log.

### CODE REVIEW

**Comment by tmenjo** [comment]
CI failed but AFAIU it is only for master, not stable branches.

**Comment by tmenjo** [comment]
@mitake May I work on this? If so, I will continue my work directly on stable-0.9 branch.

**Comment by mitake** [comment]
@tmenjo looks good to me

**Comment by mitake** [comment]
BTW, how about https://github.com/sheepdog/sheepdog/commit/c84b4fc1021df87bba161b758fb068a4333b9ad6 and https://github.com/sheepdog/sheepdog/commit/4f967e9523db5a9be353629a805cf426ff1c821c ? I'm not sure about the efficiency of reducing threads under low load by dynamic wq because it adds overhead of creating and deleting threads. Preserving a fixed number of threads would make capacity planning and performance prediction a little bit easier.

**Comment by tmenjo** [comment]
Sounds good. I will also backport that two commits, **changing the option from "-w" to "-q"** (or other unused character) because stable-0.9 already has -w option for object cache.

**Comment by mitake** [comment]
@tmenjo I see, thanks.

**Comment by tmenjo** [comment]
PR updated. Previous version is [here](https://github.com/tmenjo/sheepdog/tree/63973b9c6eb92db9cf6ac77eaee5036bab19c9c1).

## diff
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 2fd0721..983d770 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -9,7 +9,14 @@ IMPORTANT CHANGES:
    created before the given threshold. This is useful if tens of
    thousands of znodes are created in a day.
 
+NEW FEATURE:
+ - Fixed workqueue: sets and limits the number of threads in a sheep
+   process. You can get stable performance with this if tuned properly.
+
 SHEEP COMMAND INTERFACE:
+ - New option "-q" to set fixed workqueue (default: disabled i.e.
+   the number of threads increases and decreases automatically)
+   **(Note that this option will be changed to -w in version 1.0.1.)**
  - New option "-x" to set the maximum number of threads for dynamic
    workqueue. (default: decided by "max(#nodes,#cores,16)\*2" formula)
 
diff --git a/include/work.h b/include/work.h
index 2291c33..164641a 100644
--- a/include/work.h
+++ b/include/work.h
@@ -24,6 +24,7 @@ struct work_queue {
 enum wq_thread_control {
 	WQ_ORDERED, /* Only 1 thread created for work queue */
 	WQ_DYNAMIC, /* # of threads proportional to nr_nodes created */
+	WQ_FIXED, /* Fixed # of threads created */
 };
 
 static inline bool is_main_thread(void)
@@ -60,6 +61,7 @@ static inline bool is_worker_thread(void)
 int init_work_queue(size_t (*get_nr_nodes)(void));
 struct work_queue *create_work_queue(const char *name, enum wq_thread_control);
 struct work_queue *create_ordered_work_queue(const char *name);
+struct work_queue *create_fixed_work_queue(const char *name, int nr_threads);
 void queue_work(struct work_queue *q, struct work *work);
 bool work_queue_empty(struct work_queue *q);
 int wq_trace_init(void);
diff --git a/lib/work.c b/lib/work.c
index c2af9f9..3cbe4da 100644
--- a/lib/work.c
+++ b/lib/work.c
@@ -214,6 +214,9 @@ static inline uint64_t wq_get_roof(struct wq_info *wi)
 			nr = max(nr, UINT64_C(16)) * 2;
 		}
 		break;
+	case WQ_FIXED:
+		nr = wi->nr_threads;
+		break;
 	default:
 		panic("Invalid threads control %d", wi->tc);
 	}
@@ -230,6 +233,9 @@ static size_t wq_need_grow(struct wq_info *wi)
 {
 	size_t roof = 0;
 
+	if (wi->tc == WQ_FIXED)
+		return 0;
+
 	/* do not need to grow if there are enough threads */
 	if (wi->nr_threads >= uatomic_read(&wi->nr_queued_work))
 		return 0;
@@ -249,6 +255,9 @@ static size_t wq_need_grow(struct wq_info *wi)
  */
 static bool wq_need_shrink(struct wq_info *wi)
 {
+	if (wi->tc == WQ_FIXED)
+		return false;
+
 	if (uatomic_read(&wi->nr_queued_work) < wi->nr_threads / 2)
 		/* we cannot shrink work queue during protection period. */
 		return wi->tm_end_of_protection <= get_msec_time();
@@ -410,9 +419,11 @@ struct work_queue *create_work_queue(const char *name,
 	sd_init_mutex(&wi->finished_lock);
 	sd_init_mutex(&wi->pending_lock);
 
-	ret = create_worker_threads(wi, 1);
-	if (ret < 0)
-		goto destroy_threads;
+	if (tc != WQ_FIXED) {
+		ret = create_worker_threads(wi, 1);
+		if (ret < 0)
+			goto destroy_threads;
+	}
 
 	list_add(&wi->list, &wq_info_list);
 
@@ -431,6 +442,25 @@ struct work_queue *create_ordered_work_queue(const char *name)
 	return create_work_queue(name, WQ_ORDERED);
 }
 
+struct work_queue *create_fixed_work_queue(const char *name, int nr_threads)
+{
+	struct work_queue *wq;
+	struct wq_info *wi;
+	int ret;
+
+	wq = create_work_queue(name, WQ_FIXED);
+	if (!wq)
+		return NULL;
+
+	wi = container_of(wq, struct wq_info, q);
+	ret = create_worker_threads(wi, nr_threads);
+	if (ret) {
+		panic("failed to create a fixed workqueue: %s", name);
+	}
+
+	return wq;
+}
+
 bool work_queue_empty(struct work_queue *q)
 {
 	struct wq_info *wi = container_of(q, struct wq_info, q);
diff --git a/sheep/sheep.c b/sheep/sheep.c
index d3f02fe..4f483b4 100644
--- a/sheep/sheep.c
+++ b/sheep/sheep.c
@@ -152,6 +152,7 @@ static struct sd_option sheep_options[] = {
 	{'u', "upgrade", false, "upgrade to the latest data layout"},
 	{'v', "version", false, "show the version"},
 	{'w', "cache", true, "enable object cache", cache_help},
+	{'q', "wq-threads", true, "specify a number of threads for workqueue"},
 	{'W', "wildcard-recovery", false, "wildcard recovery for first time"},
 	{'x', "max-dynamic-threads", true,
 	 "specify the maximum number of threads for dynamic workqueue"},
@@ -383,6 +384,48 @@ static struct option_parser log_parsers[] = {
 	{ NULL, NULL },
 };
 
+static int wq_net_threads;
+static int wq_net_parser(const char *s)
+{
+	wq_net_threads = atoi(s);
+	return 0;
+}
+
+static int wq_gway_threads;
+static int wq_gway_parser(const char *s)
+{
+	wq_gway_threads = atoi(s);
+	return 0;
+}
+
+static int wq_io_threads;
+static int wq_io_parser(const char *s)
+{
+	wq_io_threads = atoi(s);
+	return 0;
+}
+
+static int wq_recovery_threads;
+static int wq_recovery_parser(const char *s)
+{
+	wq_recovery_threads = atoi(s);
+	return 0;
+}
+
+static int wq_async_threads;
+static int wq_async_parser(const char *s)
+{
+	wq_async_threads = atoi(s);
+	return 0;
+}
+
+static struct option_parser wq_parsers[] = {
+	{ "net=", wq_net_parser },
+	{ "gway=", wq_gway_parser },
+	{ "io=", wq_io_parser },
+	{ "recovery=", wq_recovery_parser },
+	{ "async=", wq_async_parser },
+};
 
 static const char *io_addr, *io_pt;
 static int ionic_host_parser(const char *s)
@@ -479,14 +522,44 @@ static int create_work_queues(void)
 	if (init_work_queue(get_nr_nodes))
 		return -1;
 
-	sys->net_wqueue = create_work_queue("net", WQ_DYNAMIC);
-	sys->gateway_wqueue = create_work_queue("gway", WQ_DYNAMIC);
-	sys->io_wqueue = create_work_queue("io", WQ_DYNAMIC);
-	sys->recovery_wqueue = create_work_queue("rw", WQ_DYNAMIC);
+	if (wq_net_threads) {
+		sd_info("# of threads in net workqueue: %d", wq_net_threads);
+		sys->net_wqueue = create_fixed_work_queue("net", wq_net_threads);
+	} else {
+		sd_info("net workqueue is created as dynamic");
+		sys->net_wqueue = create_work_queue("net", WQ_DYNAMIC);
+	}
+	if (wq_gway_threads) {
+		sd_info("# of threads in gway workqueue: %d", wq_gway_threads);
+		sys->gateway_wqueue = create_fixed_work_queue("gway", wq_gway_threads);
+	} else {
+		sd_info("gway workqueue is created as dynamic");
+		sys->gateway_wqueue = create_work_queue("gway", WQ_DYNAMIC);
+	}
+	if (wq_io_threads) {
+		sd_info("# of threads in io workqueue: %d", wq_io_threads);
+		sys->io_wqueue = create_fixed_work_queue("io", wq_io_threads);
+	} else {
+		sd_info("io workqueue is created as dynamic");
+		sys->io_wqueue = create_work_queue("io", WQ_DYNAMIC);
+	}
+	if (wq_recovery_threads) {
+		sd_info("# of threads in rw workqueue: %d", wq_recovery_threads);
+		sys->recovery_wqueue = create_fixed_work_queue("rw", wq_recovery_threads);
+	} else {
+		sd_info("recovery workqueue is created as dynamic");
+		sys->recovery_wqueue = create_work_queue("rw", WQ_DYNAMIC);
+	}
 	sys->deletion_wqueue = create_ordered_work_queue("deletion");
 	sys->block_wqueue = create_ordered_work_queue("block");
 	sys->md_wqueue = create_ordered_work_queue("md");
-	sys->areq_wqueue = create_work_queue("async_req", WQ_DYNAMIC);
+	if (wq_async_threads) {
+		sd_info("# of threads in async_req workqueue: %d", wq_async_threads);
+		sys->areq_wqueue = create_fixed_work_queue("async_req", wq_async_threads);
+	} else {
+		sd_info("async_req workqueue is created as dynamic");
+		sys->areq_wqueue = create_work_queue("async_req", WQ_DYNAMIC);
+	}
 	if (sys->enable_object_cache) {
 		sys->oc_reclaim_wqueue =
 			create_ordered_work_queue("oc_reclaim");
@@ -810,6 +883,10 @@ int main(int argc, char **argv)
 		case 'W':
 			wildcard_recovery = true;
 			break;
+		case 'q':
+			if (option_parse(optarg, ",", wq_parsers) < 0)
+				exit(1);
+			break;
 		case 'x':
 			max_dynamic_threads = str_to_u32(optarg);
 			if (errno != 0 || max_dynamic_threads < 1) {
```

**Comment by mitake** [comment]
@tmenjo thanks for the update, the new stable release looks good to me.

**Comment by tmenjo** [comment]
PR updated. Previous version is [here](https://github.com/tmenjo/sheepdog/tree/for-v0.9.5-2).

Commit "rpm: support for systemd and sysvinit" 454b84a0dc7f61bccff5c435f7a742c9bd14e94f is cherry-picked.

## diff

```diff
diff --git a/sheepdog.spec.in b/sheepdog.spec.in
index b4344d7..d66afcc 100644
--- a/sheepdog.spec.in
+++ b/sheepdog.spec.in
@@ -1,3 +1,5 @@
+%define use_systemd (0%{?fedora} && 0%{?fedora} >= 18) || (0%{?rhel} && 0%{?rhel} >= 7)
+
 Name: sheepdog
 Summary: The Sheepdog Distributed Storage System for QEMU
 Version: @version@
@@ -9,9 +11,14 @@ Source0: http://downloads.sourceforge.net/project/sheepdog/%{name}/%{version}/%{
 
 # Runtime bits
 Requires: corosync %{_requires}
+%if %{use_systemd}
+Requires: systemd
+BuildRequires: systemd-units
+%else
 Requires(post): chkconfig
 Requires(preun): chkconfig
 Requires(preun): initscripts
+%endif
 
 # Build bits
 BuildRequires: autoconf automake
@@ -37,6 +44,11 @@ rm -rf %{buildroot}
 
 make install DESTDIR=%{buildroot}
 
+# drop init file (systemd only)
+%if %{use_systemd}
+rm -f $RPM_BUILD_ROOT%{_initddir}/sheepdog
+%endif
+
 ## tree fixup
 # drop static libs
 rm -f %{buildroot}%{_libdir}/*.a
@@ -45,20 +57,35 @@ rm -f %{buildroot}%{_libdir}/*.a
 rm -rf %{buildroot}
 
 %post
+%if %{use_systemd}
+/usr/bin/systemctl preset sheepdog.service >/dev/null 2>&1 || :
+%else
 /sbin/chkconfig --add sheepdog
+%endif
 ln -s -f %{_sbindir}/dog %{_sbindir}/collie
 
 %preun
+
 if [ $1 -eq 0 ] ; then
-	/sbin/service sheepdog stop >/dev/null 2>&1
-	/sbin/chkconfig --del sheepdog
+    %if %use_systemd
+    /usr/bin/systemctl --no-reload disable sheepdog.service >/dev/null 2>&1 || :
+    /usr/bin/systemctl stop sheepdog.service >/dev/null 2>&1 || :
+    %else
+    /sbin/service sheepdog stop >/dev/null 2>&1
+    /sbin/chkconfig --del sheepdog
+    %endif
 fi
 
 %postun
 if [ "$1" -ge "1" ] ; then
-	/sbin/service sheepdog condrestart >/dev/null 2>&1 || :
+    %if %use_systemd
+    /usr/bin/systemctl daemon-reload >/dev/null 2>&1 || :
+    /usr/bin/systemctl try-restart sheepdog.service >/dev/null 2>&1 || :
+    %else
+    /sbin/service sheepdog condrestart >/dev/null 2>&1 || :
+    %endif
 else
-	rm -f /usr/sbin/collie
+    rm -f /usr/sbin/collie
 fi
 
 %files
@@ -68,16 +95,19 @@ fi
 %{_sbindir}/sheepfs
 %{_sbindir}/dog
 %{_sbindir}/shepherd
-%if 0%{_have_zookeeper}
-	%{_sbindir}/zk_control
-%endif
-%attr(755,-,-)%config %{_initddir}/sheepdog
 %dir %{_localstatedir}/lib/sheepdog
 %config %{_sysconfdir}/bash_completion.d/dog
 %{_mandir}/man8/sheep.8*
 %{_mandir}/man8/sheepfs.8*
 %{_mandir}/man8/dog.8*
-%{_prefix}/lib/systemd/system/sheepdog.service
+%if 0%{_have_zookeeper}
+%{_sbindir}/zk_control
+%endif
+%if %{use_systemd}
+%{_unitdir}/sheepdog.service
+%else
+%attr(755,-,-)%config %{_initddir}/sheepdog
+%endif
 
 %changelog
 * @date@ Autotools generated version <nobody@nowhere.org> - @version@-1.@alphatag@
```

**Comment by tmenjo** [comment]
Fast-forwarded into stable-0.9.

**Pull request merged**
