### PR TITLE
For release v0.9.4

### PR DESCRIPTION
**Pull request by tmenjo**
@mitake:

For next stable-0.9 release v0.9.4, I picked up recent commits and opened this PR.

Please review this when you have a time. If OK, I will continue my work for merging this into upstream stable-0.9 then tagging v0.9.4_rc0.

This PR originates latest stable-0.9 (796c88d sheep: update ledger objects in an asynchronous manner) and contains commits below. Each commit is `git cherry-pick -x`-ed from master, except 67a41e9.

### Direct I/O
* 839b879 sheep: turn on O_DIRECT just for data objects

### Multi-disk
* 9916b0a md: go down when no object store becomes available or plugged

### Deb package
* 7d4ca2d Fix bash-completion error

### Misc
* 154372e util: fix bug for sd_cond_wait_timeout()
* e249c57 lib/util: fix bug for return value check of readlink()
* da3e7a9 sheep/request: fix bug of inconsistency between data_length and data

### sheep
* 4909978 Sheep: Update the typo
* 2c039bc fix myaddr option man and help
* 6d9e0ef cleanup messages about missing features

### dog
* f4798d2 fixe incorrect man and help for vdi backup/restore

### sheep
* a9820ea sheep: fix 'http_options' warning when building
* c716f01 sheep/gateway Remove warning ‘nr_vids’ may be used uninitialized in this function
* 67a41e9 sheep: Shut up "warning: unused variable ‘rw’" **(only for stable-0.9, not picked from master)**

### CODE REVIEW

**Comment by mitake** [comment]
@tmenjo thanks, the content seems good to me. Should I merge it? Or will you push them to stable-0.9 directly?

**Comment by tmenjo** [comment]
@mitake: Thank you for your review! I will push them directly into stable-0.9.

**Comment by mitake** [comment]
@tmenjo I see, thanks!

**Comment by tmenjo** [comment]
@mitake Merged. Can I also push a release commit (updating `sheepdog_version` in configure.ac as `0.9.4_rc0`) and v0.9.4_rc0 tag?

**Comment by mitake** [comment]
sure, please do it.

**Comment by tmenjo** [comment]
I did it! Thanks!

**Pull request merged**
