### PR TITLE
sheep: create a dedicated workqueue for peer requests

### PR DESCRIPTION
**Pull request by mitake**
Current sheepdog uses the io workqueue (sys->io_wqueue) for 2 kinds of
requests: peer and local. However, this architecture can cause
deadlock in the fixed workqueue mode because of the schedules like
below:

1. node A receives a request Ra from a client, queue Ra to io_wqueue
   as a peer request
2. node B receives a request Rb from another client, queue Rb to
   io_wqueue as a peer request
3. in node A, Ra forwards the requests to node B
4. in node B, Rb forwards the requests to node A
5. if node A or node B don't have idle workers in io_workqueue, it can
   cause deadlock

This commit avoids the problem by creating a new dedicated workqueue
sys->peer_wqueue for avoiding the problem.

Signed-off-by: Hitoshi Mitake <mitake.hitoshi@lab.ntt.co.jp>

/cc @tmenjo it would be a serious problem, could you check on your side, too?

### CODE REVIEW

**Comment by mitake** [comment]
An easy way of reproduce:

```
$ for i in `seq 0 2`; do sudo sheep -c local -p 700$i -w io=1 /tmp/sheepdog/$i; done
$ dog cluster format
$ dog vdi create test1 -P
$ dog benchmark o test1 -p 7001 -t 100 -n 100
$ dog vdi delete test1 # on other terminal
```

**Comment by mitake** [comment]
The problem can also happen in dynamic workqueue because it has a limit of workers.

**Comment by tmenjo** [comment]
@mitake:

> $ dog benchmark o test1 -p 7001 -t 100 -n 100
> $ dog vdi delete test1 # on other terminal

Do you mean that you delete VDI test1 while reading/writing some data from/to it? I think such an operation  should not be done in practical use, so your way of reproduce seems improper.

**Comment by tmenjo** [comment]
I suspect that [gateway_create_and_write_obj](https://github.com/sheepdog/sheepdog/blob/master/sheep/gateway.c#L940) (run in gway thread) may cause such a deadlock issue. This function can call exec_local_req.

**Comment by mitake** [comment]
> Do you mean that you delete VDI test1 while reading/writing some data from/to it? I think such an operation should not be done in practical use, so your way of reproduce seems improper.

The example is just an example. More realistic examples, e.g. deleting multiple VDIs at the same time, will be able to cause the deadlock.

> I suspect that gateway_create_and_write_obj (run in gway thread) may cause such a deadlock issue. This function can call exec_local_req.

Yes, it seems that another gateway queue will be needed.

**Comment by mitake** [comment]
@tmenjo FYI: this chapter of Google's SRE book will be useful for understanding this kind of problem: https://landing.google.com/sre/book/chapters/addressing-cascading-failures.html

> The communication is susceptible to a distributed deadlock. Backends may use the same thread pool to wait on RPCs sent to remote backends that are simultaneously receiving requests from remote backends. Suppose backend A’s thread pool is full. Backend B sends a request to backend A and uses a thread in backend B until backend A’s thread pool clears. This behavior can cause the thread pool saturation to spread.

**Comment by tmenjo** [comment]
@mitake:

How about [peer_decref_object()](https://github.com/sheepdog/sheepdog/blob/master/sheep/ops.c#L1140)?

1. The peer_decref_object() run on an *io* thread (or a *peer* thread if this PR is merged) and can call [sd_remove_object()](https://github.com/sheepdog/sheepdog/blob/master/sheep/ops.c#L1212) to put a REMOVE_OBJ work into local *gway* workqueue. Then, the thread blocks until response.
2. A local *gway* thread handles the REMOVE_OBJ work to send REMOVE_PEER to **local or remote** *io* (or *peer*) workqueue(s). Then, the thread blocks until response.

If all the local *io* (or *peer*) threads block at step1 and the *gway* thread send REMOVE_PEER to **local** at step2, that *gway* thread seems never returned.

**Comment by mitake** [comment]
@tmenjo good catch, two more dedicated queues for gateway remove and peer remove will be required. I'll update this PR later.

**Comment by mitake** [comment]
Also `sd_read_object()` and `sd_write_object()` needs to be changed for avoiding the cyclic dependency.

**Comment by mitake** [comment]
@tmenjo updated for solving known cycling dependencies

**Comment by tmenjo** [comment]
@mitake Looks good to me!

However, The operation test `testRemoveObj` failed. I think we face this failure for the first time. I restarted CI.

CI said:
```
testRemoveObj (__main__.ThreeNodesTwoCopiesTest) ... 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by mitake** [comment]
@tmenjo CI passed successfully, so I'm merging this. Thanks for your review.

**Pull request merged**
