### PR TITLE
sheep: add a new option for using fixed workqueues for stable perform…

### PR DESCRIPTION
**Pull request by mitake**
…ance

This commit adds a new option -w to sheep for using fixed workqueues.
Example of usage:
$ sheep -w gway=100,net=300

If the option isn't passed, sheep uses unlimited queues but it is
highly dicouraged for stable and high IOPS.

Based on @luckychen 's report, the patch doubles IOPS with well
configured parameters: 40,000 -> 83,460 IOPS

Signed-off-by: Hitoshi Mitake <mitake.hitoshi@lab.ntt.co.jp>

### CODE REVIEW

**Comment by mitake** [comment]
@luckychen could you share your configuration, environment, and result for an exmaple of use case? Just copying messages in gitter is ok.

**Comment by mitake** [comment]
@tmenjo how about backporting this commit to stable branches?

**Comment by tmenjo** [comment]
@mitake: Umm... Unfortunately stable-0.9 branch still have object cache option `sheep -w`. Naive backporting may cause confusion.

**Comment by mitake** [comment]
@tmenjo ah I see. creating stable-1.0 and backport it (or just create stable-1.0 from the current master) would be ok

**Pull request merged**
